### Get information
GET http://localhost:3000/tasks

### To send information
POST http://localhost:3000/tasks
Content-Type: application/json

{  
    "id": 3,
    "title": "Eat Bananas",
    "completed": false
}